Repository wechaty/jekyll, pull requests merged in 2024-02, with the labels that each got.

#178 Update Wechaty Contributor Profile
  jekyll/_contributors/wangwanlin.md
  jekyll/assets/contributors/wangwanlin/avatar.webp
Labels: size:S, lgtm

#180 Unveiling the Treasures of Collaboration: My Wechaty GSOD'21 Gifts!
  jekyll/_posts/2024-02-18-wechaty-gsod-gifts.md
  jekyll/assets/2024/02-wechaty-gsod-gifts/gsod-wechaty-gifts.webp
Labels: size:M, lgtm

#181 Fix for the image ratio issue in the recent blog post
  jekyll/assets/2024/02-wechaty-gsod-gifts/gsod-wechaty-gifts.webp
Labels: size:XS, lgtm
